// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

#pragma once

#include <string>
#include <unordered_map>
#include <vector>

namespace onnxruntime {  // forward declarations
class Model;
class GraphTransformer;
class NodeArg;
}  // namespace onnxruntime

namespace onnxruntime {
class MLValue;
using InputDefList = std::vector<const onnxruntime::NodeArg*>;
using OutputDefList = std::vector<const onnxruntime::NodeArg*>;

using NameMLValMap = std::unordered_map<std::string, MLValue>;

/**
* Configuration information for a single Run.
*/
struct RunOptions {
  unsigned run_log_verbosity_level = 0;  ///< applies to a particular Run() invocation
  std::string run_tag;                   ///< to identify logs generated by a particular Run() invocation
};

}  // namespace onnxruntime
