ARG OS_VERSION=16.04
FROM ubuntu:${OS_VERSION}

ADD scripts /tmp/scripts
ENV PATH="/opt/cmake/bin:${PATH}"
RUN /tmp/scripts/install_ubuntu.sh && /tmp/scripts/install_deps.sh && rm -rf /tmp/scripts

WORKDIR /root

ENV LD_LIBRARY_PATH /usr/local/openblas/lib:$LD_LIBRARY_PATH

ARG BUILD_UID=1000
ARG BUILD_USER=lotusdev
RUN adduser --gecos 'LOTUS Build User' --disabled-password $BUILD_USER --uid $BUILD_UID
USER $BUILD_USER
WORKDIR /home/$BUILD_USER

