#include "core/framework/data_types.h"

namespace Lotus
{
    LOTUS_REGISTER_TENSOR_TYPE(int);
    LOTUS_REGISTER_TENSOR_TYPE(float);
    LOTUS_REGISTER_TENSOR_TYPE(bool);
    LOTUS_REGISTER_TENSOR_TYPE(std::string);
    LOTUS_REGISTER_TENSOR_TYPE(uint8_t);
    LOTUS_REGISTER_TENSOR_TYPE(uint16_t);
    LOTUS_REGISTER_TENSOR_TYPE(int16_t);
    LOTUS_REGISTER_TENSOR_TYPE(int64_t);
    LOTUS_REGISTER_TENSOR_TYPE(double);
    LOTUS_REGISTER_TENSOR_TYPE(uint32_t);
    LOTUS_REGISTER_TENSOR_TYPE(uint64_t);
}
